apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    chains.tekton.dev/signed: "true"
  labels:
    tekton.dev/pipeline: pacman-verification
  generateName: pacman-verification-pr-
spec:
  taskRunSpecs:
  - pipelineTaskName: verify-enterprise-contract
    serviceAccountName: job-runner
  params:
    ## Image repository parameters
  - name: git-repo-url
    value: https://github.com/marrober/pacman.git
  - name: git-revision
    value: 4164c348676c112f83f255c26a0360eb965991c1
    ## Verify enterprise contract
  - name: quay-instance-url
    value: "quay.io"
  - name: quay-account                   
    value: "marrober"
  - name: quay-repository                
    value: "pacman"
  - name: image-tag
    value: "bd3mi"
  - name: component_id
    value: "pacman"
  - name: rekor_host
    value: http://rekor-server.trusted-artifact-signer.svc
  - name: policy_configuration
    value: 'git::github.com/redhat-gpe/config//default'
  - name: tuf_mirror
    value: http://tuf.trusted-artifact-signer.svc
  pipelineRef:
    name: pacman-verification
  taskRunTemplate:
    serviceAccountName: image-pusher
  timeouts:
    pipeline: 1h0m0s
  workspaces:
    - name: images-url
      emptyDir: {}