apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-env-configmap
  namespace: pacman-ci
data:
  ARGOCD_SERVER: openshift-gitops-server-openshift-gitops.apps.cluster-4v8ng.dynamic.redhatworkshops.io
