apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-env-configmap
  namespace: pacman-ci
data:
  ARGOCD_SERVER: oc get route/openshift-gitops-server -n openshift-gitops -o jsonpath='{.spec.host}{"\n"}'

