apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-env-configmap
  namespace: pacman-ci
data:
  ARGOCD_SERVER: openshift-gitops-server-openshift-gitops.apps.cluster-v8vmm.v8vmm.sandbox1487.opentlc.com

