apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: argocd-sync-and-wait
spec:
  params:
    - description: name of the application to sync
      name: application-name
      type: string
    - default: HEAD
      description: the revision to sync to
      name: revision
      type: string
    - default: '--'
      name: flags
      type: string
    - default: v2.2.2
      name: argocd-version
      type: string
  stepTemplate:
    envFrom:
      - configMapRef:
          name: argocd-env-configmap
      - secretRef:
          name: argocd-env-secret
    name: ''
    resources: {}
  steps:
    - image: 'quay.io/argoproj/argocd:$(params.argocd-version)'
      name: login
      resources: {}
      script: >
        yes | argocd login --skip-test-tls "$ARGOCD_SERVER" --username="$ARGOCD_USERNAME" --password="$ARGOCD_PASSWORD";

        argocd app sync "$(params.application-name)" --revision
        "$(params.revision)" "$(params.flags)"

        argocd app wait "$(params.application-name)" --health "$(params.flags)"