apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: verify-commit
spec:
  params:
  - description: TUF mirror
    name: tuf-mirror
    type: string
    default: http://tuf.trusted-artifact-signer.svc
  - description: Email address of committer
    name: certificate-identity
    type: string
    default: user1@demo.redhat.com
  - description: OIDC issuer
    name: oidc-issuer
    type: string
    default: https://keycloak-rhsso.apps.cluster-v42rv.sandbox795.opentlc.com/auth/realms/sigstore
  - description: Rekor URL
    name: rekor-url
    type: string
    default: http://rekor-server.trusted-artifact-signer.svc
  - name: tuf-root-hash
    type: string
  - name: git-repo-name
    type: string
  description: This task verifies the latest commit signature
  stepTemplate:
    env:
      - name: GITSIGN_REKOR_URL
        value: $(params.rekor-url)
  steps:
  - image: image-registry.openshift-image-registry.svc:5000/pacman-ci/terminal:2.1
    name: git-verify
    script: |
      cd /workspace/repository/$(params.git-repo-name)
      ls -al
      git config --global --add safe.directory /workspace/repository/$(params.git-repo-name)
      cosign initialize --mirror=$(params.tuf-mirror) --root=$(params.tuf-mirror)/root.json --root-checksum=$(params.tuf-root-hash)
      git show -s
      gitsign verify --certificate-identity-regexp=$(params.certificate-identity) --certificate-oidc-issuer=$(params.oidc-issuer) HEAD \
      || (echo "Unable to verify commit signature!  Please ensure that the RHEL9 VM was used for source code commits or you have configured GitSign on your development machine correctly." && exit 1)
    workingDir: /workspace/repository
  workspaces:
  - name: repository
