apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: verify-commit
spec:
  params:
  - description: TUF mirror
    name: tuf-mirror
    type: string
    default: http://tuf.trusted-artifact-signer.svc
  - description: Email address of committer
    name: certificate-identity
    type: string
  - description: OIDC issuer
    name: oidc-issuer
    type: string
  - description: Rekor URL
    name: rekor-url
    type: string

  - name: tuf-root-hash
    type: string
  - name: git-repo-name
    type: string
  description: This task verifies the latest commit signature
  stepTemplate:
    env:
      - name: GITSIGN_REKOR_URL
        value: $(params.rekor-url)
  steps:
  - image: image-registry.openshift-image-registry.svc:5000/pacman-ci/terminal:2.1
    name: git-verify
    script: |
      cd /workspace/repository/$(params.git-repo-name)
      ls -al
      echo "GITSIGN REKOR URL environment setting"
      echo "----------------------------------"
      echo $GITSIGN_REKOR_URL
      echo "----------------------------------"
      echo "git config information"
      echo "----------------------------------"
      git --no-pager config --list
      echo "----------------------------------"
      git config --global --add safe.directory /workspace/repository/$(params.git-repo-name)
      echo "----------------------------------" 
      echo "cosign version"
      echo "----------------------------------" 
      cosign version
      echo "----------------------------------" 
      echo "cosign environment"
      echo "----------------------------------" 
      cosign env
      echo "----------------------------------" 
      echo "Cosign initialize"
      echo "----------------------------------"   
      cosign initialize --mirror=$(params.tuf-mirror) --root=$(params.tuf-mirror)/root.json --root-checksum=$(params.tuf-root-hash)
      echo "----------------------------------"  
      echo "git show - display the commit ID"
      echo "----------------------------------"
      git show -s
      echo "----------------------------------"
      echo "gitsign command version and connection information"
      echo "----------------------------------"
      gitsign --version
      echo "----------------------------------"
      echo "gitsign verify"
      echo "----------------------------------"
      gitsign verify --certificate-identity-regexp=$(params.certificate-identity) --certificate-oidc-issuer=$(params.oidc-issuer) HEAD \
      || (echo "Unable to verify commit signature!  Please ensure that the RHEL9 VM was used for source code commits or you have configured GitSign on your development machine correctly." && exit 1)
      echo "----------------------------------"
    workingDir: /workspace/repository
  workspaces:
  - name: repository
