apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: pacman
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Project to show how Argo and Tekton can be used together
  sourceRepos:
  - '*'
  - https://github.com/marrober/pacman
  - https://marrober.github.io/helm-charts/

  destinations:
  - server: https://kubernetes.default.svc
    namespace: '*'

  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
  - group: 'rbac.authorization.k8s.io'
    kind: ClusterRole
  - group: 'rbac.authorization.k8s.io'
    kind: ClusterRoleBinding

  roles:
  - name: developer
    groups:
    - developers
    policies:
    - p, proj:pacman:developer, applications, get, *, allow
    - p, proj:pacman:developer, applications, sync, *, allow  