apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: pacman
  namespace: openshift-gitops
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # Project description
  description: Project to show how Argo and Tekton can be used together

  # Allow manifests to deploy from specific Git repos
  sourceRepos:
  - '*'
  - https://github.com/marrober/pacman
  - https://marrober.github.io/helm-charts/

  # Limit the namespaces to which the project can deploy
  destinations:
  - server: https://kubernetes.default.svc
    namespace: '*'
#  - server: https://api.celeron.demolab.local:6443
#    namespace: '*'

  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
  - group: 'rbac.authorization.k8s.io'
    kind: ClusterRole
  - group: 'rbac.authorization.k8s.io'
    kind: ClusterRoleBinding

  namespaceResourceBlacklist:
  namespaceResourceWhitelist:


  roles:
    - p, proj:pacman:mark, applications, get, pacman-01/*, allow
    - p, proj:pacman:mark, applications, sync, pacman-01/*, allow  