apiVersion: apps/v1
kind: Deployment
metadata:
  name: smee-pacman
  labels:
    app: smee-development
    deployment: smee-pacman
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smee-development
      deployment: smee-pacman
  template:
    metadata:
      labels:
        app: smee-development
        deployment: smee-pacman
    spec:
      containers:
        - image: image-registry.openshift-image-registry.svc:5000/pacman-ci/gosmee:latest
          imagePullPolicy: IfNotPresent
          name: gosmee
          args:
            [
              "client",
              "--saveDir",
              "/tmp/save",
              "https://smee.io/vSantlzgFXh7ddOf",
              "http://pacman-ci-listener-el-pacman-ci.apps.skylake.demolab.local"
            ]
