kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: buildah
spec:
  lookupPolicy:
    local: false
  tags:
    - name: latest
      from:
        kind: DockerImage
        name: 'image-registry.openshift-image-registry.svc:5000/pacman-ci/buildah:latest'
      importPolicy:
        importMode: Legacy
      referencePolicy:
        type: Source