kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: gosmee
spec:
  lookupPolicy:
    local: false
  tags:
    - name: latest
      from:
        kind: DockerImage
        name: 'quay.io/marrober/gosmee:latest'
      importPolicy:
        importMode: Legacy
      referencePolicy:
        type: Source