kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: ose-cli
  namespace: pacman-ci
spec:
  lookupPolicy:
    local: false
  tags:
    - name: latest
      annotations: null
      from:
        kind: DockerImage
        name: 'registry.redhat.io/openshift4/ose-cli:latest'
      importPolicy:
        importMode: Legacy
      referencePolicy:
        type: Source