kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: nodejs
  namespace: pacman-ci
spec:
  lookupPolicy:
    local: false
  tags:
    - name: nodejs-22-1-177
      from:
        kind: DockerImage
        name: 'registry.redhat.io/rhel9/nodejs-22:1-1777524498'
      importPolicy:
        importMode: Legacy
      referencePolicy:
        type: Source
    - name: nodejs-22-9.8-178
      from:
        kind: DockerImage
        name: 'registry.redhat.io/rhel9/nodejs-22:9.8-1783399991'
      importPolicy:
        importMode: Legacy
      referencePolicy:
        type: Source
    - name: nodejs-h-22.23.1
      from:
        kind: DockerImage
        name: 'registry.access.redhat.com/hi/nodejs:22.23.1'
      importPolicy:
        importMode: Legacy
      referencePolicy:
        type: Source
    - name: nodejs-h-24.18.0
      from:
        kind: DockerImage
        name: 'registry.access.redhat.com/hi/nodejs:24.18.0'
      importPolicy:
        importMode: Legacy
      referencePolicy:
        type: Source
    - name: 1-1778142166
      from:
        kind: DockerImage
        name: 'registry.redhat.io/rhel9/nodejs-20:1-1778142166'
      importPolicy:
        importMode: Legacy
      referencePolicy:
        type: Source





        