kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: rhel8-nodejs-16
spec:
  lookupPolicy:
    local: false
  tags:
    - name: latest
      from:
        kind: DockerImage
        name: registry.redhat.io/rhel8/nodejs-16
      importPolicy:
        importMode: Legacy
      referencePolicy:
        type: Source
