kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: terminal
  namespace: pacman-ci
spec:
  lookupPolicy:
    local: false
  tags:
    - name: latest
      from:
        kind: DockerImage
        name: 'quay.io/marrober/devex-terminal-4:full-terminal-1.6'
      importPolicy:
        importMode: Legacy
      referencePolicy:
        type: Source
