kind: ServiceAccount
apiVersion: v1
metadata:
  name: image-pusher
  namespace: pacman-ci
secrets:
  - name: github-access-token
  - name: quay-auth-secret
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: image-pusher-edit
  namespace: pacman-ci
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- kind: ServiceAccount
  name: image-pusher
  namespace: pacman-ci
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: image-pusher-pipelines-scc-role
  namespace: pacman-ci
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pipelines-scc-clusterrole
subjects:
- kind: ServiceAccount
  name: image-pusher
  namespace: pacman-ci