apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- role-bindings/argo-cd-admin.yaml
- pipeline.yaml
- tasks/acs-image-build-check.yaml
- tasks/build.yaml
- tasks/push-image-to-imagestream.yaml
