apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  labels:
    app.kubernetes.io/instance: pacman-git
    app.kubernetes.io/name: pacman-git
    pipeline.openshift.io/runtime: nodejs
    pipeline.openshift.io/runtime-version: 16-ubi8
    pipeline.openshift.io/type: kubernetes
  name: pacman-argocd
spec:
  params:
    ## ArgoCD Sync
  - name: argocd-project-name-development
    type: string
  - name: argocd-revision
    type: string
  - name: argocd-flags
    type: string
  - name: argocd-version
    type: string
  tasks:
##------------------------------------------------------------------
# Force ArgoCD sync
##------------------------------------------------------------------
  - name: sync-argocd
    params:
    - name: application-name
      value: $(params.argocd-project-name-development)
    - name: revision
      value: $(params.argocd-revision)
    - name: flags
      value: $(params.argocd-flags)
    - name: argocd-version
      value: $(params.argocd-version)
    taskRef:
      kind: Task
      name: argocd-sync-and-wait
