apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    chains.tekton.dev/signed: "true"
  labels:
    app.kubernetes.io/instance: pacman-git
    app.kubernetes.io/name: pacman-git
    pipeline.openshift.io/runtime: nodejs
    pipeline.openshift.io/runtime-version: 16-ubi8
    pipeline.openshift.io/type: kubernetes
    tekton.dev/pipeline: pacman
  generateName: pacman-pr-
spec:
  params:
    ## Repository parameters
  - name: GIT_REPO
    value: https://github.com/marrober/pacman.git
  - name: GIT_REVISION
    value: ""
    ## Verify git commit parameters
  - name: certificate-identity
    value: user1@demo.redhat.com
    # value: $(tt.params.git-committer)
  - name: oidc-issuer
    value:  https://https://keycloak-keycloak-system.apps.cluster-4v8ng.dynamic.redhatworkshops.io/auth/realms/trusted-artifact-signer
  - name: rekor-url
    value: http://rekor-server.trusted-artifact-signer.svc
  - name: tuf-mirror
    value: http://tuf.trusted-artifact-signer.svc
    ## Image build parameters
  - name: IMAGE_NAME
    value: default-route-openshift-image-registry.apps.cluster-sl5m4-1.sl5m4-1.sandbox3223.opentlc.com/$(context.taskRun.namespace)/pacman
  - name: PATH_CONTEXT
    value: src
  - name: STORAGE_DRIVER
    value: vfs   
  - name: TLSVERIFY
    value: false
    ## Image validation parameters
  - name: acs_central_endpoint
    value: acs-secret
  - name: acs_api_token
    value: acs-secret
  - name: roxctl-output-format
    value: "table"
    ## Update Argocd application and commit to GitHub
  - name: repo_type
    value: github.com
  - name: cd-git-url
    value: marrober/pacman
  - name: cd-git-repo-name
    value: pacman
  - name: cd-git-repo-path-to-content-development
    value: cd/env/01-dev
  - name: cd-git-commit-comment-dev
    value: "Update from ci process - dev"
  - name: cd-git-user-name
    value: "Mark Roberts"
  - name: cd-git-user-email
    value: "mroberts@redhat.com"
  - name: argocd-project-name-development
    value: "pacman-dev-01"
  - name: argocd-revision
    value: "main"
  - name: argocd-version
    value: "v2.4.14"
  - name: quay-instance-url
    value: "quay.io"
  - name: quay-account
    value: "marrober"
  - name: quay-repository
    value: "pacman"    
  pipelineRef:
    name: pacman
  taskRunTemplate:
    serviceAccountName: image-pusher
  timeouts:
    pipeline: 1h0m0s
  workspaces:
  - name: workspace
    volumeClaimTemplate:
      metadata:
        creationTimestamp: null
        labels:
          tekton.dev/pipeline: pacman
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  - name: files
    volumeClaimTemplate:
      metadata:
        creationTimestamp: null
        labels:
          tekton.dev/pipeline: pacman
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi
    