apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    chains.tekton.dev/signed: "true"
  labels:
    app.kubernetes.io/instance: pacman-git
    app.kubernetes.io/name: pacman-git
    pipeline.openshift.io/runtime: nodejs
    pipeline.openshift.io/runtime-version: 16-ubi8
    pipeline.openshift.io/type: kubernetes
    tekton.dev/pipeline: pacman
  generateName: pacman-pr-
spec:
  params:
    ## repository parameters
  - name: GIT_REPO
    value: https://github.com/marrober/pacman.git
  - name: GIT_REVISION
    value: ""
    ## Image build parameters
  - name: IMAGE_NAME
    value: image-registry.openshift-image-registry.svc:5000/$(context.taskRun.namespace)/pacman
  - name: PATH_CONTEXT
    value: src
  - name: STORAGE_DRIVER
    value: vfs   
  - name: TLSVERIFY
    value: false
    ## Image validation parameters
  - name: acs_central_endpoint
    value: acs-secret
  - name: acs_api_token
    value: acs-secret
  - name: roxctl-output-format
    value: "table"
  pipelineRef:
    name: pacman
  taskRunTemplate:
    serviceAccountName: pipeline
  timeouts:
    pipeline: 1h0m0s
  workspaces:
  - name: workspace
    volumeClaimTemplate:
      metadata:
        creationTimestamp: null
        labels:
          tekton.dev/pipeline: pacman
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  - name: files
    volumeClaimTemplate:
      metadata:
        creationTimestamp: null
        labels:
          tekton.dev/pipeline: pacman
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi
    