apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-env-configmap
data:
  ARGOCD_SERVER: openshift-gitops-server-openshift-gitops.apps.cluster-vhdnd.sandbox2089.opentlc.com
  ARGOCD_USERNAME: admin