kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ec-jobrunner-edit
subjects:
  - kind: ServiceAccount
    name: job-runner
    namespace: pacman-ci
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit