apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    eventlistener: pacman-ci-pipeline-listener-interceptor
  name: pacman-ci-listener-el
spec:
  port:
    targetPort: http-listener
  to:
    kind: Service
    name: el-pacman-ci-pipeline-listener-interceptor
