apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: pacman-ci-template
spec:
  params:
  - name: gitrepository.url
  - name: gitrevision
  - name: branch
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: pacman-ci-pipeline-1-run-tr-
    spec:
      serviceAccountName: pipeline
      pipelineRef:
        name: pacman
      params:
        - name: git-url
          value: $(tt.params.gitrepository.url)
        - name: git-revision
          value: $(tt.params.gitrevision)
        - name: branch
          value: $(tt.params.branch)
        - name: IMAGE_NAME
          value: image-registry.openshift-image-registry.svc:5000/$(context.taskRun.namespace)/pacman
        - name: PATH_CONTEXT
          value: src
        - name: STORAGE_DRIVER
          value: vfs   
        - name: TLSVERIFY
          value: false
          ## Image validation parameters
        - name: acs_central_endpoint
          value: acs-secret
        - name: acs_api_token
          value: acs-secret
        - name: roxctl-output-format
          value: "table"
          ## Update Argocd application and commit to GitHub
        - name: GIT_REPO
          value: $(tt.params.gitrepository.url)
        - name: GIT_REVISION
          value: $(tt.params.gitrevision)
        - name: repo_type
          value: github.com
        - name: cd-git-url
          value: marrober/pacman
        - name: cd-git-repo-name
          value: pacman
        - name: cd-git-repo-path-to-content-development
          value: cd/env/01-dev
        - name: argocd-application-file
          value: pacman-development.yaml
        - name: cd-git-commit-comment-dev
          value: "Update from triggered ci process - dev"
        - name: cd-git-user-name
          value: "Mark Roberts"
        - name: cd-git-user-email
          value: "mroberts@redhat.com"
      workspaces:
      - name: files
        volumeClaimTemplate:
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 20Gi
      - name: resources
        volumeClaimTemplate:
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 5Gi
