apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- argocd-app.yaml
- ci-automation/tekton-resources.yaml
- env/01-dev/argo-cd-admin.yaml
- env/01-dev/image-pull-role-binding.yaml
- env/01-dev/pacman-development.yaml
- env/01-dev/argocd-platform-cm.yaml
