FROM default-route-openshift-image-registry.apps.cluster-vhdnd.sandbox2089.opentlc.com/pacman-ci/nodejs-16:latest
USER 0
COPY . /opt/app-root/src/
RUN chmod a+w /var/log
USER 1001
CMD ["npm", "start"]
