apiVersion: v1
kind: Secret
metadata:
  name: argocd-env-secret
  namespace: pacman-ci
data:
  ARGOCD_AUTH_TOKEN: ZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SnBjM01pT2lKaGNtZHZZMlFpTENKemRXSWlPaUp3Y205cU9uQmhZMjFoYmpwd1lXTnRZVzR0YzNsdVl5SXNJbTVpWmlJNk1UY3pNRGc1TVRReE9Td2lhV0YwSWpveE56TXdPRGt4TkRFNUxDSnFkR2tpT2lJeU1UTTFOakUwTXkxaE9UWXdMVFE1WVRZdE9USmxOeTAxTkdFMlkyTmxPR0ZpTkRraWZRLmFaLVBpS1hkQ2ltb2Fpd3hlVk5qR09XMGJyam1BOTBCMTdSVkdFYXE4MzQ=