kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pull-image-from-pacman-ci
  namespace: pacman-ci
subjects:
- kind: ServiceAccount
  name: default
  namespace: pacman-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'system:image-puller'