apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- dev-namespace.yaml
- dev-namespace-control.yaml
- deployment.yaml
- service.yaml
- route.yaml
- admin-job/role-and-binding.yaml
- admin-job/replicaset-cleanup-cronjob.yaml

images:
- name: quay.io/marrober/pacman
  newTag: dqq4c-ee6a7
