apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- dev-namespace.yaml
- dev-namespace-control.yaml
- deployment.yaml
- service.yaml
- route.yaml
- admin-job/role-and-binding.yaml
- admin-job/replicaset-cleanup-cronjob.yaml

images:
- name: default-route-openshift-image-registry.apps.ocp4.mr-openshift.co.uk/pacman-ci/pacman
  newTag: ddpxb-141fc
- name: quay.io/marrober/pacman
  newTag: gxs2j-6894b
