apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    chains.tekton.dev/signed: "true"
  labels:
    pipeline.openshift.io/runtime: nodejs
    pipeline.openshift.io/runtime-version: 16-ubi8
    pipeline.openshift.io/type: kubernetes
    tekton.dev/pipeline: ${{ values.application_name }}-pipeline
  generateName: ${{ values.application_name }}-pr-
spec:
  params:
    ## repository parameters
  - name: GIT_REPO
    value: ${{ values.source_repository }}
  - name: GIT_REVISION
    value: ""
    ## Image build parameters
  - name: IMAGE_NAME
    value: image-registry.openshift-image-registry.svc:5000/$(context.taskRun.namespace)/${{ values.application_name }}
  - name: PATH_CONTEXT
    value: src
  - name: STORAGE_DRIVER
    value: vfs   
  - name: TLSVERIFY
    value: false
    ## Image validation parameters
  - name: acs_central_endpoint
    value: acs-secret
  - name: acs_api_token
    value: acs-secret
  - name: roxctl-output-format
    value: "table"
    ## Update Argocd application and commit to GitHub
  - name: repo_type
    value: github.com
  - name: cd-git-url
    value: marrober/${{ values.application_name }}
  - name: cd-git-repo-name
    value: ${{ values.application_name }}
  - name: cd-git-repo-path-to-content-development
    value: cd/env/01-dev
  - name: argocd-application-file
    value: ${{ values.application_name }}-development.yaml
  - name: cd-git-commit-comment-dev
    value: "Update from ci process - dev"
  - name: cd-git-user-name
    value: " ${{ values.cd-git-username }} "
  - name: cd-git-user-email
    value: " ${{ values.cd-git-email-address }} "
  pipelineRef:
    name: ${{ values.application_name }}-pipeline
  taskRunTemplate:
    serviceAccountName: pipeline
  timeouts:
    pipeline: 1h0m0s
  workspaces:
  - name: workspace
    volumeClaimTemplate:
      metadata:
        creationTimestamp: null
        labels:
          tekton.dev/pipeline: pacman
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  - name: files
    volumeClaimTemplate:
      metadata:
        creationTimestamp: null
        labels:
          tekton.dev/pipeline: pacman
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi
    